language: haskell

ghc:
  - "8.4"
  - "8.6"
  - "8.8"
  - "8.10"
  - "9.0"
  - "9.2"

install:
  - cabal update
  - cabal install --enable-tests --dependencies-only

script:
  - cabal configure --enable-tests
  - cabal build
  - cabal test
