language: haskell

ghc:
  - "7.10"
  - "8.0"
  - "8.2"
  - "8.4"

install:
  - cabal update
  - cabal install --enable-tests --dependencies-only

script:
  - cabal configure --enable-tests
  - cabal build
  - cabal test
