name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.4', '8.6', '8.8', '8.10', '9.0', '9.2']
        cabal: ['latest']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }} (cabal-${{ matrix.cabal }})
    steps:
      - uses: actions/checkout@v3

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Install dependencies
        run: |
          cabal v2-update
          cabal v2-build --dependencies-only --enable-tests --enable-benchmarks

      - name: Build
        run: cabal v2-build --enable-tests --enable-benchmarks

      - name: Run tests
        continue-on-error: true
        run: cabal v2-test

      - name: Build samples
        run: cabal v2-build --flags=examples
